# Generated by Django 4.1.3 on 2022-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('img', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
