# Generated by Django 4.1.3 on 2022-11-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='label_number',
            field=models.IntegerField(default=-1, max_length=256),
        ),
    ]
