# Generated by Django 4.1.3 on 2022-11-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=256)),
                ('price_in_cents_cad', models.IntegerField(max_length=256)),
            ],
        ),
    ]
